### ISSUE TITLE
a

### ISSUE THREAD

**Issue by villagerBrine** [calico-team/raffle-sp23-public#2]

**Comment by alfphaderp** [comment]
sorry to hear that!

have u considered asking ur team member to share the prize

**Comment by villagerBrine** [comment]
yes im sure they wont :(

**Comment by alfphaderp** [comment]
have u tried asking politely

**Comment by villagerBrine** [comment]
we sent him an email asking politely

**Comment by villagerBrine** [comment]
apparently hes giving :shrug: how do i close this

**Comment by villagerBrine** [comment]
a

**Comment by alfphaderp** [comment]
b
